### ISSUE TITLE
woo #100

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#102]
#100

**Comment by thecoder876** [comment]
@1hostjs/devs YES SIR

**Comment by thecoder876** [comment]
oh my god GITHUB IS BEING HACKED - THAT TEAM JUST SUDDENLY GOT DELETED

**Comment by wgyt** [comment]
> oh my god GITHUB IS BEING HACKED - THAT TEAM JUST SUDDENLY GOT DELETED

that was an accident

**Comment by thecoder876** [comment]
> > oh my god GITHUB IS BEING HACKED - THAT TEAM JUST SUDDENLY GOT DELETED
> 
> that was an accident

@wgyt ohhhh ok
