### ISSUE TITLE
Contributors: get recognised

### ISSUE THREAD

**Issue by thecoder876** [1hostjs/hosting#21]
Whether it's code, docs or just ideas, you can get recognised as a 1Host.js contributor. To add yourself to the list on the readme (see [here](https://github.com/1hostjs/hosting#contributors)), comment the following:

    @all-contributors please add @<username> for <contributions>

Replace `<username>` with your username, and `<contributions>`  with the words for your contributions (get them from [the emoji key guide](https://allcontributors.org/docs/en/emoji-key)).

Happy contributing!

The 1Host team

**Comment by thecoder876** [comment]
@all-contributors please add @wgyt for bug, code, doc, design, ideas, infra, maintenance and review

**Comment by retronbv** [comment]
@all-contributors please add @retronbv for bug, code, doc, design, ideas, infra, maintenance and review

**Comment by thecoder876** [comment]
@all-contributors please add @thecoder876 for code, ideas, maintenance, projectManagement and review

**Comment by thecoder876** [comment]
@retronbv oops we have to remove our contributions from the 1.x.x repo first

**Comment by thecoder876** [comment]
@wgyt there's something wrong with your pr
![conflict](https://user-images.githubusercontent.com/76265544/114177500-62cec800-9934-11eb-802f-8387259216cf.png)

**Comment by thecoder876** [comment]
@all-contributors please add @wgyt for bug, code, doc, design, ideas, infra, maintenance and review

**Comment by thecoder876** [comment]
🤦‍♂️

**Comment by wgyt** [comment]
closing this because this doesn't need to be open for it to work

**Comment by wgyt** [comment]
@allcontributors add @GrahamSH-LLK for bug, code, doc, design, ideas, infra, maintenance and review

**Comment by thecoder876** [comment]
> closing this because this doesn't need to be open for it to work

@wgyt yeah but then people think it doesn't work

**Comment by thecoder876** [comment]
@all-contributors please add @cary-uwu for ideas

**Comment by wgyt** [comment]
@all-contributors please add @dependabot for security
