### ISSUE TITLE
[Developer Facing] GItlocalize broke

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#26]
**What would this change?**
idk
**How would this affect people?**
fixes the L10N system
**Other info**
none

**Comment by wgyt** [comment]
possibly move to transifex, they have an open source plan
cc @1hostjs/devs

**Comment by thecoder876** [comment]
@wgyt i haven't added the repo in the dashboard yet, and WHAT THEY HAVE A FREE PLAN?!

**Comment by thecoder876** [comment]
close because it's not broken, but we should still probably move to transifex

**Comment by wgyt** [comment]
> close because it's not broken, but we should still probably move to transifex

it is broken because the dashboard shows the old repo

**Comment by wgyt** [comment]
> @wgyt i haven't added the repo in the dashboard yet, and WHAT THEY HAVE A FREE PLAN?!

they have a free plan for open source projects
https://www.transifex.com/open-source/

**Comment by thecoder876** [comment]
> > close because it's not broken, but we should still probably move to transifex
> 
> it is broken because the dashboard shows the old repo

@wgyt yeah i haven't added the new repo and removed the old repo yet, that's why

**Comment by GrahamSH-LLK** [comment]
> @wgyt i haven't added the repo in the dashboard yet, and WHAT THEY HAVE A FREE PLAN?!

Yeah, haven't you noticed SA uses it? We have no funding.

**Comment by wgyt** [comment]
I'm setting it up right now

**Comment by thecoder876** [comment]
> > @wgyt i haven't added the repo in the dashboard yet, and WHAT THEY HAVE A FREE PLAN?!
> 
> Yeah, haven't you noticed SA uses it? We have no funding.

@GrahamSH-LLK ik they do, but i didn't know it was paid when i first discovered that they use it

**Comment by wgyt** [comment]
We might need to change some code

**Comment by thecoder876** [comment]
> We might need to change some code

@wgyt hmm

**Comment by wgyt** [comment]
If we want to use Transifex Native we need to
https://docs.transifex.com/javascript-sdk/quickstart-transifex-native-and-javascript

**Comment by thecoder876** [comment]
btw #27 for discussion

**Comment by thecoder876** [comment]
> If we want to use Transifex Native we need to
> https://docs.transifex.com/javascript-sdk/quickstart-transifex-native-and-javascript

@wgyt new dependency?

**Comment by wgyt** [comment]
> > If we want to use Transifex Native we need to
> > https://docs.transifex.com/javascript-sdk/quickstart-transifex-native-and-javascript
> 
> @wgyt new dependency?

I guess, but we can remove some  cough cough *consola*

**Comment by thecoder876** [comment]
> > > If we want to use Transifex Native we need to
> > > https://docs.transifex.com/javascript-sdk/quickstart-transifex-native-and-javascript
> > 
> > 
> > [ping removed] new dependency?
> 
> I guess, but we can remove some cough cough _consola_

lol

**Comment by wgyt** [comment]
can someone update the code? (because I am in class in person)

**Comment by thecoder876** [comment]
@GrahamSH-LLK ^^

**Comment by GrahamSH-LLK** [comment]
I'll set it up

**Comment by thecoder876** [comment]
@wgyt i might do it, but what is the "public facing token"?

**Comment by thecoder876** [comment]
> I'll set it up

@GrahamSH-LLK oh ok

**Comment by GrahamSH-LLK** [comment]
I'm have this pretty much ready, hold on.

**Comment by thecoder876** [comment]
> I'm have this pretty much ready, hold on.

@GrahamSH-LLK ok

**Comment by wgyt** [comment]
> @wgyt i might do it, but what is the "public facing token"?

i can give you the information on DIscord
