### ISSUE TITLE
heroku support?

### ISSUE THREAD

**Issue by thecoder876** [1hostjs/hosting#32]
it supports node.js, so we could have a command like this

    1host heroku deploysite

auth:

    1host heroku login

**Comment by GrahamSH-LLK** [comment]
AFAIX netlify only supports node for _generating_ static content.

**Comment by thecoder876** [comment]
> AFAIX netlify only supports node for _generating_ static content.

@GrahamSH-LLK oh

**Comment by RedGuy12** [comment]
What's the difference between seeing it up on heroku and setting it up anywhere else?

**Comment by GrahamSH-LLK** [comment]
> What's the difference between seeing it up on heroku and setting it up anywhere else?

Literally nothing

**Comment by RedGuy12** [comment]
Well actually you do need a `Procfile` with the content `web: npm start` but that's easy and if you don't have it that's the fallback anyway.
________________________________
