### ISSUE TITLE
transifex cli?

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#34]
shouldn't @transifex/cli be a dev dependency?
cc @GrahamSH-LLK

**Comment by GrahamSH-LLK** [comment]
Yep

**Comment by thecoder876** [comment]
@wgyt hmm yeah it should

**Comment by retronbv** [comment]
isn’t it transfiex?

**Comment by wgyt** [comment]
> isn’t it transfiex?

idk

**Comment by wgyt** [comment]
done https://github.com/1hostjs/hosting/commit/8fc944e2e9a2aa7c76a60e75ca65285a94f7cc21
