### ISSUE TITLE
[Feature Request] Use different port

### ISSUE THREAD

**Issue by GrahamSH-LLK** [1hostjs/hosting#35]
If the port is taken, it should try a random port until it gets an open one

**Comment by wgyt** [comment]
> If the port is taken, it should try a random port until it gets an open one

don't we get the port from 1host,config.js? if thats the case they should just use process.env.PORT

**Comment by GrahamSH-LLK** [comment]
> > If the port is taken, it should try a random port until it gets an open one
> 
> don't we get the port from 1host,config.js? if thats the case they should just use process.env.PORT

We do get it from `1host.config.js`, but someone might like port 3000, and have another process already running there. We should make sure we don't crash from this.

**Comment by wgyt** [comment]
> We do get it from `1host.config.js`, but someone might like port 3000, and have another process already running there. We should make sure we don't crash from this.

fair point, we should check if the port is free, but how? something like https://www.npmjs.com/package/portfinder?

**Comment by wgyt** [comment]
we could also use try and catch
