### ISSUE TITLE
[Feature Request] add module config and hosts support

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#36]
cc @GrahamSH-LLK

**Comment by thecoder876** [comment]
@wgyt what hosts?

**Comment by wgyt** [comment]
> @wgyt what hosts?

modules that run on only one site

**Comment by wgyt** [comment]
@GrahamSH-LLK how would I check the variable config if the stynax is the same as errorHandler?

**Comment by wgyt** [comment]
this is the last issue we need to solve for [2.1.0](https://github.com/1hostjs/hosting/milestone/1) to be ready to be released
