### ISSUE TITLE
2.x.x ISNT PUBLISHED TO NPM

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#39]
cc @1hostjs/devs

**Comment by GrahamSH-LLK** [comment]
Wat?!?!?!?!?!?!?!?!?!??!?!?! If it isn't, let me push changes first.

**Comment by wgyt** [comment]
@GrahamSH-LLK can you please do #36 before we publish 2.0.0

**Comment by GrahamSH-LLK** [comment]
Sure.

**Comment by wgyt** [comment]
@GrahamSH-LLK can you just publish what we have?

**Comment by GrahamSH-LLK** [comment]
Can you

**Comment by wgyt** [comment]
> Can you

I can't, I'm on a school chromebook :|

**Comment by wgyt** [comment]
done
