### ISSUE TITLE
Is this the same as express.static?

### ISSUE THREAD

**Issue by Explosion-Scratch** [1hostjs/hosting#43]
Is this the same as this:
```js
const express = require("express");
const app = express();

express.static("/");

app.listen(3000);
```

**Comment by GrahamSH-LLK** [comment]
> Is this the same as this:
> 
> ```js
> const express = require("express");
> const app = express();
> 
> express.static("/");
> 
> app.listen(3000);
> ```

No, 1host isn't static

**Comment by wgyt** [comment]
@Explosion-Scratch OneHost isn't static as modules can do almost anything, not just serving files.
_note: this is better suited for the Q&A section of OneHost discussions_
