### ISSUE TITLE
[docs] change the logo

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#50]
use this logo: https://cdn.onedot.cf/brand/SVG/NoPadding/One%20Host%20NoPad.svg and remove the text

**Comment by GrahamSH-LLK** [comment]
NO i like our current logo

**Comment by wgyt** [comment]
Disagree. @devxan's new logo design is better.
How about we make a poll?

**Comment by devxan** [comment]
Sure ¯\_(ツ)_/¯

**Comment by wgyt** [comment]
> Sure ¯_(ツ)_/¯
> (How do you make polls?)

react with a thumbs up or down to this comment 
![Screenshot 2021-04-14 at 15 30 25](https://user-images.githubusercontent.com/68466727/114768014-5da7b980-9d36-11eb-818b-26b2a92a96eb.png)

**Comment by GrahamSH-LLK** [comment]
👍 = Xan
👎 = old

**Comment by devxan** [comment]
Let's ask the dev server.
