### ISSUE TITLE
[Feature Request] remove dependencies

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#56]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
remove all the stuff except @transifex/native and os-locale
**Describe alternatives you've considered**
replace them with built in tools
**Additional context**
no

**Comment by GrahamSH-LLK** [comment]
Dependencies are real, they're 100% fine

**Comment by wgyt** [comment]
> Dependencies are real, they're 100% fine

I know, but all consola does is add emojis

**Comment by wgyt** [comment]
all chalk does is add color
boxen adds boxes
wrap-ansi wraps text
can't we make our own version of this stuff?
how hard is it to add emojis and wrap text?

**Comment by GrahamSH-LLK** [comment]
> all chalk does is add color
> boxen adds boxes
> wrap-ansi wraps text
> can't we make our own version of this stuff?
> how hard is it to add emojis and wrap text?

Chalk is hard
Boxen is hard
wrap-ansi is hard
Consola is not just emojis
