### ISSUE TITLE
[Feature Request] cli options

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#57]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
add cli options like
- start
- start in a different directory
- config
- help
- etc.
**Describe alternatives you've considered**
manually doing this
**Additional context**
examples:
```bash
1host help
1host start
1host start --location=./tests/posix/
1host config
```

**Comment by GrahamSH-LLK** [comment]
Find a good cli library and roll with it

**Comment by wgyt** [comment]
> Find a good cli library and roll with it

I guess?

**Comment by wgyt** [comment]
I almost finished this except for config stuff dealing with modules.
