### ISSUE TITLE
Feature Request: Add Global Config Files

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#66]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when having to change the config for each module for stuff like colors.

**Describe the solution you'd like**
Add global config in an object called globalConfig 

**Describe alternatives you've considered**
Spending more time by having to change the config for each module for stuff like colors.

**Additional context**
I said this in the discord server,

**Comment by thecoder876** [comment]
@wgyt idk, maybe make a config.json that has some default settings?

**Comment by wgyt** [comment]
> @wgyt idk, maybe make a config.json that has some default settings?

no, this would be a globalConfig object in modules.json

**Comment by thecoder876** [comment]
> > [ping removed] idk, maybe make a config.json that has some default settings?
> 
> no, this would be a globalConfig object in modules.json

@wgyt ohhhhh ok
