### ISSUE TITLE
Add yarn.lock

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#67]
yarn > npm
cc @GrahamSH-LLK

**Comment by GrahamSH-LLK** [comment]
Nah, they're both good

**Comment by wgyt** [comment]
> Nah, they're both good

I guess. But can't we have a package.json and package-lock.json/yarn.lock ?

**Comment by wgyt** [comment]
also @GrahamSH-LLK should we publish to [other js package managers](https://stackshare.io/npm/alternatives)?
