### ISSUE TITLE
Rename wgytcraft to 1host.js

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#68]
not my idea. my sister's idea
cc @wgytcraft/public

**Comment by GrahamSH-LLK** [comment]
Yeah, wgytcraft sounds like something from minecraft

**Comment by wgyt** [comment]
> Yeah, wgytcraft sounds like something from minecraft

fun fact: wgytcraft.cf was going to be a minecraft server :rofl:

**Comment by GrahamSH-LLK** [comment]
I know, you said that.

**Comment by GrahamSH-LLK** [comment]
But what should it be called

**Comment by wgyt** [comment]
> But what should it be called

We need ideas 🤔

**Comment by GrahamSH-LLK** [comment]
@everyone We need ideas

**Comment by retronbv** [comment]
Bruh this isnt discord, you just pinged the user named everyone

**Comment by retronbv** [comment]
Also: i like wgytcraft

**Comment by GrahamSH-LLK** [comment]
> Bruh this isnt discord, you just pinged the user named everyone

I know, that was the joke. Also, it's a org, so I didn't ping anyone.

**Comment by wgyt** [comment]
An idea:
1Host

**Comment by GrahamSH-LLK** [comment]
Maybe...

**Comment by wgyt** [comment]
> Maybe...

Does anyone have a good idea? or ANY ideas?

**Comment by GrahamSH-LLK** [comment]
Let's keep wgytcraft cause we'd have to change npm

**Comment by wgyt** [comment]
@GrahamSH-LLK how about
onehost.js

**Comment by GrahamSH-LLK** [comment]
1host.js?

**Comment by wgyt** [comment]
> 1host.js?

New logo idea:
![image](https://user-images.githubusercontent.com/68466727/111353760-f970d780-865b-11eb-9718-4c532de7b1b7.png)

**Comment by GrahamSH-LLK** [comment]
That's okay, how'd you make it

**Comment by wgyt** [comment]
> That's okay, how'd you make it

some AI logo generator made thing for the text but I made the tilted globe in scratch

**Comment by GrahamSH-LLK** [comment]
Yeah, we can try to find the font. I hate those things, plus we don't have full rights to our own logo

**Comment by wgyt** [comment]
> Yeah, we can try to find the font. I hate those things, plus we don't have full rights to our own logo

We should find a simmilar font and use that with the globe I made

**Comment by wgyt** [comment]
@GrahamSH-LLK Is [this](https://fonts.google.com/specimen/Baloo+Tammudu+2?preview.text=1host.js&preview.text_type=custom) font good?

**Comment by wgyt** [comment]
All we need to do is get the font in the shade of red, add the globe to it and then we are done
this might take a while

**Comment by wgyt** [comment]
@GrahamSH-LLK 
![image](https://user-images.githubusercontent.com/68466727/111359241-a437c480-8661-11eb-837e-b167ddb06ce8.png)
how is this?

**Comment by GrahamSH-LLK** [comment]
Looks good!

**Comment by wgyt** [comment]
Time to download the svg version

**Comment by wgyt** [comment]
@wgytcraft/public should we finalize this change?

**Comment by GrahamSH-LLK** [comment]
The globe can be our new gh logo

**Comment by GrahamSH-LLK** [comment]
Can I have a SVG for the docs?

**Comment by wgyt** [comment]
> Can I have a SVG for the docs?

sure. I can't upload the file here, but here's the code:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="517pt" height="198pt" version="1.0" viewBox="0 0 517.000000 198.000000" xmlns="http://www.w3.org/2000/svg">
<g transform="translate(0 198) scale(.1 -.1)" fill="#f63202">
<path d="m858 1573c-17-4-18-34-18-448 0-482-1-475 55-475 57 0 55-10 55 269v257l41 24c63 35 164 40 216 10 74-41 78-55 81-313l3-228 24-11c13-6 35-8 49-4l26 6v233c0 131-5 248-11 270-13 47-60 102-113 130-59 31-200 31-268 0l-48-22v135c0 121-2 136-20 154-19 19-36 23-72 13z"/>
<path d="m4105 1555c-14-13-25-33-25-45 0-29 44-70 75-70 61 0 87 81 39 119-35 27-59 26-89-4z"/>
<path d="m386 1478c-131-58-151-79-120-125 18-29 21-28 127 21l77 35v-349c0-200 4-360 10-374 10-28 46-42 79-31 21 6 21 10 21 425v419l-22 15c-12 9-29 16-38 16-8 0-68-24-134-52z"/>
<path d="m1960 1495c-167-37-321-163-374-307-78-210-39-410 113-571 80-84 124-110 226-132 95-21 233-16 310 10 75 27 180 100 232 163 86 105 120 220 110 370-17 259-214 454-482 475-44 4-94 0-135-8zm83-103c-59-36-65-38-115-31-29 4-62 8-73 9-20 1-20 1 0 12 42 24 132 47 190 47l60 1-62-38zm199-18c5-4-39-94-45-94-1 0-28 11-61 24l-59 24 34 18c57 29 118 42 131 28zm118-116c6-22 10-53 8-70l-3-30-40 32c-22 17-46 35-54 40-11 6-8 17 15 59 29 51 29 51 46 30 10-11 23-39 28-61zm-470 3c-10-14-30-39-43-55l-23-28-57 32c-31 17-57 34-57 36 0 23 124 55 177 46 23-4 23-4 3-31zm199-17c34-15 61-31 61-37 0-16-83-157-93-157-19 0-157 84-157 96 0 17 99 124 115 124 8 0 41-12 74-26zm394-101c19-49 35-164 20-148-51 55-63 84-63 157 0 63 2 70 13 53 8-11 21-39 30-62zm-754 6c31-17 57-32 59-34 1-1-12-32-29-69-30-63-32-66-46-47-28 41-53 107-53 144 0 20 3 37 7 37 3 0 31-14 62-31zm569-30c69-56 68-47 30-151-11-32-25-58-30-58-20 0-169 93-166 104 7 27 84 156 93 156 6 0 39-23 73-51zm-359-90c39-22 73-45 76-49 5-9-80-166-95-175-13-8-125 90-128 112-4 25 52 153 66 153 6 0 42-18 81-41zm-239-163c0-13-3-44-6-70-6-41-8-44-20-29-22 29-54 142-54 191v45l40-57c22-31 40-67 40-80zm745 72c14-29 25-70 25-91v-37l-37 19c-70 37-68 32-42 100 13 33 25 61 27 61s14-24 27-52zm-269-45c46-27 84-53 84-59 0-10-28-51-79-114l-19-24-69 22c-115 37-114 34-57 135 27 48 51 87 53 87s41-21 87-47zm-296-161c0-13-63-112-71-112-23 0-45 97-40 177 1 21 4 20 56-19 30-22 55-43 55-46zm504 42c25-14 46-30 46-35 0-18-84-49-132-49h-47l41 55c22 30 42 55 43 55s23-12 49-26zm-371-102c37-16 69-31 72-34s-21-19-54-37c-55-29-127-42-144-25-4 5 50 121 58 124 0 0 31-13 68-28zm297-58c0-12-127-62-175-69-55-7-54-5 10 44 34 25 49 30 103 30 34 1 62-2 62-5z"/>
<path d="m3373 1503c-10-4-13-87-13-369 0-343 1-367 20-403 29-57 92-85 191-86 106 0 156 35 131 90-10 23-12 23-54 8-60-21-123-12-157 21l-26 26-3 205-3 205h108c59 0 113 4 120 8 12 8 16 24 14 60-1 22-4 22-121 22h-120v100c0 88-2 100-19 110-21 10-47 12-68 3z"/>
<path d="m2847 1316c-96-26-147-87-147-174 0-99 46-141 195-182 44-11 93-26 108-32 41-16 67-55 67-98 0-100-155-132-294-60-65 33-86 29-86-19 0-62 89-103 225-104 98-2 151 11 202 49 42 32 68 100 59 160-13 98-72 145-231 185-132 33-176 87-125 152 42 53 163 61 248 18 54-27 70-27 78 4 12 50-21 79-114 101-70 17-122 17-185 0z"/>
<path d="m4557 1320c-53-14-87-33-122-69-25-27-30-41-33-96-7-109 36-152 193-195 44-11 93-26 108-32 41-16 67-55 67-98 0-100-155-132-294-60-65 33-86 29-86-19 0-103 287-147 413-65 53 35 81 100 74 166-12 101-71 149-232 189-132 33-176 87-125 152 42 53 163 61 248 18 54-28 70-27 78 6 9 35-4 54-57 80-51 26-172 38-232 23z"/>
<path d="m4113 1303c-10-4-13-88-13-371 0-416-3-429-73-467-29-15-36-24-31-40 23-78 143-44 188 54 20 44 21 64 24 418 3 365 3 372-17 392s-51 26-78 14z"/>
<path d="m3826 768c-41-58 3-137 69-124 39 8 55 31 55 76 0 46-25 70-73 70-26 0-40-6-51-22z"/>
</g>
</svg>
```

**Comment by wgyt** [comment]
but @GrahamSH-LLK don't change it ***yet***

**Comment by GrahamSH-LLK** [comment]
Sorry, I already did. Let's just change now.

**Comment by wgyt** [comment]
> Sorry, I already did. Let's just change now.

Time to beg my sister for the laptop she has so I can do npm stuff

**Comment by wgyt** [comment]
@GrahamSH-LLK I'm going to rename the org

**Comment by GrahamSH-LLK** [comment]
Okay!

**Comment by wgyt** [comment]
We will all need to change our dev enviroments lol

**Comment by wgyt** [comment]
time to rename @wgytcraftdeps

**Comment by retronbv** [comment]
Lol

**Comment by wgyt** [comment]
We all need to read this:
https://docs.github.com/en/github/using-git/changing-a-remotes-url

**Comment by GrahamSH-LLK** [comment]
I'm gonna grab 1host.js.org

**Comment by wgyt** [comment]
> I'm gonna grab 1host.js.org

I'll update the docs and package.json

**Comment by retronbv** [comment]
+1

**Comment by retronbv** [comment]
I renamed the discord server

**Comment by wgyt** [comment]
can someone update https://github.com/1hostjs/1hostjs.github.io/blob/main/static/icon.png

**Comment by GrahamSH-LLK** [comment]
We need the svg of the globe.

**Comment by wgyt** [comment]
> We need the svg of the globe.

Just make it the globe icon png from https://avatars.githubusercontent.com/u/79263876?s=200&v=5

**Comment by retronbv** [comment]
I made announcement in the discord server

**Comment by wgyt** [comment]
@GrahamSH-LLK your pr screwed up the domain
its 1hostjs.github.io not 1host.github,io

**Comment by retronbv** [comment]
F

**Comment by wgyt** [comment]
it works! 🥳 
time to make a new npm org

**Comment by retronbv** [comment]
rolling eyes emoji

**Comment by thecoder876** [comment]
@wgyt i totally agree, the new name is great
