### ISSUE TITLE
NPM Doesn't Publish at all

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#69]
do we have to make a new repo so github packages works? do we need to do some commands in the command line?
cc @GrahamSH-LLK

**Comment by wgyt** [comment]
It publishes to github packages but not npm:
https://github.com/1hostjs/hosting/actions/runs/659020359

**Comment by GrahamSH-LLK** [comment]
Github packages != npm, weirdly enough. It's an alternative to npm. Our NPM workflow is broken

**Comment by wgyt** [comment]
> Github packages != npm, weirdly enough. It's an alternative to npm. Our NPM workflow is broken

Yeah. NPM just broke on us :P should I try to publish 1.0.0 and go to 1.1.0 and then 1.1.1 then 1.1.2 then 1.1.3 then 1.1.4 then 1.1.5 then 1.1.6

**Comment by GrahamSH-LLK** [comment]
Do you own the 1hostjs (not 1host.js org)?

**Comment by GrahamSH-LLK** [comment]
If not, let's just kill GH packages all together

**Comment by wgyt** [comment]
> Do you own the 1hostjs (not the 1host.js org)?

@GrahamSH-LLK I own both the 1hostjs and 1host.js orgs

**Comment by GrahamSH-LLK** [comment]
Then publish at 1host/hosting and we should be good!

**Comment by wgyt** [comment]
> Then publish at 1host/hosting and we should be good!

do you mean 1hostjs?

**Comment by GrahamSH-LLK** [comment]
Yep

**Comment by thecoder876** [comment]
@wgyt we should just update through npm if gh packages doesn't send to npm

**Comment by wgyt** [comment]
> @wgyt we should just update through npm if gh packages doesn't send to npm

I want this workflow to work because it would make life easier

**Comment by thecoder876** [comment]
> also... don't lock issues

@wgyt this is dev only, so why not?

**Comment by wgyt** [comment]
we don't need to publish it automatically
