### ISSUE TITLE
'modules' is not defined.

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#81]
#### Message: `'modules' is not defined.`
@wgyt This should be module.exports

    
#### Occurred on:
+ **Commit**:  087ec182654940bf05dd6448e3c4dae2b90b9777
+ **File**:    [src/index.ts](https://github.com/wgytcraft/hosting/blob/087ec182654940bf05dd6448e3c4dae2b90b9777/src/index.ts)
+ **LineNum**: [1](https://github.com/wgytcraft/hosting/blob/087ec182654940bf05dd6448e3c4dae2b90b9777/src/index.ts#L1)
+ **Code**:    `modules.exports = function (modules: any, dirname: string, port: number) {`

    
#### Currently on:
+ **Commit**:  255c010ac8d91ecd86e95b1691398d137e29db74
+ **File**:    [src/index.ts](https://github.com/wgytcraft/hosting/blob/255c010ac8d91ecd86e95b1691398d137e29db74/src/index.ts)
+ **LineNum**: [1](https://github.com/wgytcraft/hosting/blob/255c010ac8d91ecd86e95b1691398d137e29db74/src/index.ts#L1)

**Comment by thecoder876** [comment]
Imao

**Comment by wgyt** [comment]
invalid
