### ISSUE TITLE
**FAKE**: I give this project to @GrahamSH-LLK

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#82]
I give up all control and give it to GrahamSH. Also, my address is [REDACTED].

**Comment by thecoder876** [comment]
> I give up all control and give it to GrahamSH. Also, my address is [REDACTED].

@wgyt this has got to be a joke

**Comment by GrahamSH-LLK** [comment]
I found a codacy vuln (ish).

**Comment by thecoder876** [comment]
> I found a codacy vuln (ish).

@GrahamSH-LLK OOOOOOF

**Comment by thecoder876** [comment]
knew it

**Comment by thecoder876** [comment]
quick note: this is because @GrahamSH-LLK found a codacy vuln(ish) that lets him send messages as wgyt.
# **THIS IS FAKE I REPEAT THIS IS FAKE**

**Comment by retronbv** [comment]
Lmao

**Comment by thecoder876** [comment]
@retronbv wtf

**Comment by thecoder876** [comment]
quick note: this is because @GrahamSH-LLK found a codacy vuln(ish) that lets him send messages as wgyt.

# **THIS IS FAKE I REPEAT THIS IS FAKE**

**Comment by retronbv** [comment]
Just delete the issue for gods sake

**Comment by thecoder876** [comment]
> Just delete the issue for gods sake

@retronbv bruh i can't

**Comment by retronbv** [comment]
> > Just delete the issue for gods sake
> 
> @retronbv bruh i can't

Ugh

**Comment by wgyt** [comment]
wow, thanks
