### ISSUE TITLE
Windows uses \\ but we use /

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#87]
**Describe the bug**

Our require statements use / but it should use \\\\ because windows isn't posix compliant unlike *nix and macos

**To Reproduce**

Run 1host.js on windows

**Expected behavior**

should work

**Additional context**

nope

**Comment by thecoder876** [comment]
@wgyt 🤦‍♂️ classic windows
thanks ms, thanks

**Comment by retronbv** [comment]
please refer to it as 1host.js lmao

**Comment by wgyt** [comment]
easy fix: if on windows, CHANGE THE / TO \\\\

**Comment by thecoder876** [comment]
> easy fix: if on windows, CHANGE THE / TO \\

@wgyt lol
